name: xp_downloader
description: "x,p video downloader app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ^3.6.1

dependencies:
  archive: ^4.0.2
  cherry_toast: ^1.12.0
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_markdown: ^0.7.6+2
  flutter_spinkit: ^5.2.1
  translator: ^1.0.3+1
  html: ^0.15.5
  intl: ^0.20.2
  media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
  provider: ^6.1.2
  t_release: ^0.0.4
  than_pkg: ^1.6.5
  timeago: ^3.2.2
  uuid: ^4.5.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  # dart run change_app_package_name:main [com.new.package.name]
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  # commmand dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
